# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://edxu96.github.io/elec_consumption/"

git_url = "https://github.com/edxu96/elec_consumption/tree/master/"

def custom_doc_links(name): return None
